/**
 * Bake decrypted env values into src/generated/runtime-env.ts (gitignored).
 *
 * TODO: only needed for Vercel — the function bundle has no runtime access to
 * the repo's `.env.prod`, so src/server.ts falls back to the generated module.
 *
 * Usage (cwd apps/backend, wrapped by its `build` / `build:prod` scripts):
 *   dotenvx run -f ../../.env.prod -- bun ../../packages/env/scripts/gen-runtime-env.ts  # real values
 *   bun ../../packages/env/scripts/gen-runtime-env.ts --stub                             # empty stub
 *
 * The stub is what the root `postinstall` writes (run from the repo root as
 * `bun packages/env/scripts/gen-runtime-env.ts --stub`) so typecheck/dev work
 * before any decrypt has happened.
 */
import {
  OPTIONAL_SERVER_ENV_KEYS,
  type RuntimeEnv,
  SERVER_ENV_KEYS,
} from "../env-keys";

const stub = process.argv.includes("--stub");
const outPath = `${import.meta.dir}/../src/generated/runtime-env.ts`;

const values: RuntimeEnv = {};

if (!stub) {
  for (const key of SERVER_ENV_KEYS) {
    const value = process.env[key];
    if (!value) {
      // WARN: fail the build early — a missing required var only shows up
      // as a Zod startup crash inside the deployed function otherwise
      if ((OPTIONAL_SERVER_ENV_KEYS as readonly string[]).includes(key)) {
        console.warn(
          `[gen-runtime-env] optional var ${key} not set — skipping`,
        );
        continue;
      }
      throw new Error(`missing ${key} — run under dotenvx with .env.prod`);
    }
    values[key] = value;
  }
}

const banner = stub
  ? "// AUTO-GENERATED stub (packages/env/scripts/gen-runtime-env.ts --stub) — rewritten by build:prod.\n"
  : "// AUTO-GENERATED by packages/env/scripts/gen-runtime-env.ts — DO NOT EDIT OR COMMIT.\n";

const source = `${banner}import type { RuntimeEnv } from "../../env-keys";

const runtimeEnv: RuntimeEnv = ${JSON.stringify(values, null, 2)};

export default runtimeEnv;
`;

await Bun.write(outPath, source);
console.log(
  `[gen-runtime-env] wrote ${outPath} (${Object.keys(values).length} values${stub ? ", stub" : ""})`,
);
