import type { Metadata } from "next";
import { Geist, Geist_Mono, Inter } from "next/font/google";
import "./globals.css";
import { FaviconSync } from "@/components/branding/favicon";
import { ThemeProvider } from "@/components/theme/theme-provider";
import { cn } from "@/lib/utils";

const inter = Inter({ subsets: ["latin"], variable: "--font-sans" });

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

/**
 * Applies the persisted/system theme to <html> before first paint to prevent a
 * light→dark flash on every load. Mirrors `theme-provider.tsx` (storageKey
 * "theme", values light/dark/system, class strategy).
 */
const THEME_INIT_SCRIPT = `(function () {
  try {
    var root = document.documentElement;
    var stored = localStorage.getItem("theme");
    var theme =
      stored === "light" || stored === "dark" || stored === "system"
        ? stored
        : "system";
    var resolved =
      theme === "system"
        ? window.matchMedia("(prefers-color-scheme: dark)").matches
          ? "dark"
          : "light"
        : theme;
    root.classList.remove("light", "dark");
    root.classList.add(resolved);
    root.style.colorScheme = resolved;
  } catch (e) {}
})();`;

export const metadata: Metadata = {
  title:
    "Obelisk – OUTCOMES-BASED EDUCATIONAL LEARNING AND INTELLIGENT SYSTEM KIT FOR JOSE MARIA COLLEGE FOUNDATION INC.",
  description: "Generated by create next app",
  icons: {
    icon: [
      {
        url: "/metadata/obelisk-logo.svg",
        type: "image/svg+xml",
        media: "(prefers-color-scheme: light)",
      },
      {
        url: "/metadata/obelisk-logo-dark.svg",
        type: "image/svg+xml",
        media: "(prefers-color-scheme: dark)",
      },
    ],
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      suppressHydrationWarning
      className={cn(
        "h-full",
        "antialiased",
        geistSans.variable,
        geistMono.variable,
        "font-sans",
        inter.variable,
      )}
    >
      <head>
        {/* biome-ignore lint/security/noDangerouslySetInnerHtml: static theme-init script, no user input */}
        <script dangerouslySetInnerHTML={{ __html: THEME_INIT_SCRIPT }} />
      </head>
      <ThemeProvider>
        <FaviconSync />
        <body className="min-h-full flex flex-col">{children}</body>
      </ThemeProvider>
    </html>
  );
}
