/**
 * Bake decrypted env values into src/generated/runtime-env.ts (gitignored).
 *
 * TODO: only needed for Vercel — the function bundle has no runtime access to
 * the repo's `.env.prod`, so utils/env.ts falls back to the generated module.
 *
 * Usage:
 *   dotenvx run -f ../../.env.prod -- bun scripts/gen-runtime-env.ts  # real values
 *   bun scripts/gen-runtime-env.ts --stub                          # empty stub
 *
 * The stub is what `postinstall` writes so typecheck/dev work before any
 * decrypt has happened.
 */
import {
	BACKEND_ENV_KEYS,
	OPTIONAL_BACKEND_ENV_KEYS,
	type RuntimeEnv,
} from "../utils/env-keys";

const stub = process.argv.includes("--stub");
const outPath = `${import.meta.dir}/../src/generated/runtime-env.ts`;

const values: RuntimeEnv = {};

if (!stub) {
	for (const key of BACKEND_ENV_KEYS) {
		const value = process.env[key];
		if (!value) {
			// WARN: fail the build early — a missing required var only shows up
			// as a Zod startup crash inside the deployed function otherwise
			if ((OPTIONAL_BACKEND_ENV_KEYS as readonly string[]).includes(key)) {
				console.warn(
					`[gen-runtime-env] optional var ${key} not set — skipping`,
				);
				continue;
			}
			throw new Error(`missing ${key} — run under dotenvx with .env.prod`);
		}
		values[key] = value;
	}
}

const banner = stub
	? "// AUTO-GENERATED stub (scripts/gen-runtime-env.ts --stub) — rewritten by build:vercel.\n"
	: "// AUTO-GENERATED by scripts/gen-runtime-env.ts — DO NOT EDIT OR COMMIT.\n";

const source = `${banner}import type { RuntimeEnv } from "../../utils/env-keys";

const runtimeEnv: RuntimeEnv = ${JSON.stringify(values, null, 2)};

export default runtimeEnv;
`;

await Bun.write(outPath, source);
console.log(
	`[gen-runtime-env] wrote ${outPath} (${Object.keys(values).length} values${stub ? ", stub" : ""})`,
);
